imports:
    - { resource: config.yml }

framework:
    assets:
        packages:
            webpack:

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

zenstruck_asset_manifest:
    manifest_file: "%kernel.root_dir%/../web/dist/asset-manifest.json"