fos_js_routing:
    resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'

app:
    resource: '@AppBundle/Controller/'
    type: annotation

auth:
    path: /user/auth.{_format}
    requirements: {_format: "json|xml|yml"}
    options:
        expose: true

logout:
    path: /logout
    options:
        expose: true

react_router:
    path: "/{url}"
    defaults:
        url: ""
        _controller: AppBundle:Default:reactRouter
    requirements:
        url: ".*"
