fos_js_routing:
    resource: @FOSJsRoutingBundle/Resources/config/routing/routing.xml

app:
    resource: @AppBundle/Controller/
    type: annotation

login_check:
    path: /login_check
    options:
        expose: true

logout:
    path: /logout
    options:
        expose: true

react_router:
    path: "{url}"
    defaults:
        url: ""
        _controller: AppBundle:Default:reactRouter
