security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        db_users:
            entity:
                class: AppBundle:User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            provider: db_users
            form_login:
                login_path: login
                check_path: login_check
                success_handler: authentication_handler
                failure_handler: authentication_handler
                username_parameter: username
                password_parameter: password
            logout:
                path:   /logout
                success_handler: authentication_handler
